server:
  port: 8001
mysql:
  version: 8.0.28
spring:
mybatis:
  type-aliases-package: org.example.usve.model.po
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.example.usve.dao.mapper: debug
redisargs:
  defaultReceiveAddress: ${spring.application.name}-${spring.profiles}-defaultReceiveAddress