local:
  mysql:
    ip: 192.168.120.101
    port:
      master: 42066
      slave: 42067
  redis:
    ip: 192.168.120.101
    pass: 123456
spring:
  datasource:
    slave:
      jdbc-url: jdbc:mysql://172.221.234.190:3307/usve?serverTimezone=UTC&characterEncoding=utf8
      username: usve
      password: usvetanqin
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: HikariCP
        auto-commit: false
    master:
      jdbc-url: jdbc:mysql://172.221.234.190:3306/usve?serverTimezone=UTC&characterEncoding=utf8
      username: usve
      password: usvetanqin
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: HikariCP
        auto-commit: false