spring:
  datasource:
    slave:
      jdbc-url: jdbc:mysql://127.0.0.1:3307/usve?serverTimezone=UTC&characterEncoding=utf8
      username: usve
      password: usvetanqin
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: HikariCP
        auto-commit: false
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/usve?serverTimezone=UTC&characterEncoding=utf8
      username: usve
      password: usvetanqin
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: HikariCP
        auto-commit: false