spring:
  datasource:
    slave:
      jdbc-url: jdbc:mysql://172.221.234.190:3307/recipe?serverTimezone=UTC&characterEncoding=utf8
      username: reip
      password: reiptanqin
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: HikariCP
        auto-commit: false
    master:
      jdbc-url: jdbc:mysql://172.221.234.190:3306/recipe?serverTimezone=UTC&characterEncoding=utf8
      username: reip
      password: reiptanqin
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: HikariCP
        auto-commit: false