local:
  mysql:
    ip: 192.168.120.101
    port:
      master: 42066
      slave: 42067
  redis:
    ip: 192.168.120.101
    pass: 123456
spring:
  datasource:
    slave:
      jdbc-url: jdbc:mysql://${local.mysql.ip}:${local.mysql.port.slave}/recipe?serverTimezone=UTC&characterEncoding=utf8
      username: reip
      password: reiptanqin
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: HikariCP
        auto-commit: false
    master:
      jdbc-url: jdbc:mysql://${local.mysql.ip}:${local.mysql.port.master}/recipe?serverTimezone=UTC&characterEncoding=utf8
      username: reip
      password: reiptanqin
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: HikariCP
        auto-commit: false
  redis:
    cluster:
      nodes:
        - ${local.redis.ip}:7361
        - ${local.redis.ip}:7362
        - ${local.redis.ip}:7363
        - ${local.redis.ip}:7364
        - ${local.redis.ip}:7365
        - ${local.redis.ip}:7366
    password: ${local.redis.pass}
config:
  info:
    nacos-address: 192.168.120.101:8848
    nacos-namespace: 8a1cad62-3e0b-452d-8010-d963704fb1ac
    nacos-data-id: FILE_UP
    nacos-group: DEFAULT_GROUP
    nacos-timeout: 30000