config:
  info:
    nacos-address: 192.168.120.101:8848
    nacos-namespace: 8a1cad62-3e0b-452d-8010-d963704fb1ac
    nacos-data-id: gateway-router
    nacos-group: DEFAULT_GROUP
    nacos-timeout: 30000