version: "3"
services:
  redis-node1:
    image: redis:6.2.6
    container_name: redis-node1
    restart: always
    privileged: true
    volumes:
      - /root/volume/redis/node-1/data:/data
      - /root/volume/redis/node-1/conf/redis.conf:/etc/redis/redis.conf
    ports:
      - "7361:7361"
      - "17361:17361"
    command:
      /bin/bash -c "redis-server /etc/redis/redis.conf"